 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/itineraries", type: :request do
  # Itinerary. As you add validations to Itinerary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Itinerary.create! valid_attributes
      get itineraries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      itinerary = Itinerary.create! valid_attributes
      get itinerary_url(itinerary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_itinerary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      itinerary = Itinerary.create! valid_attributes
      get edit_itinerary_url(itinerary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Itinerary" do
        expect {
          post itineraries_url, params: { itinerary: valid_attributes }
        }.to change(Itinerary, :count).by(1)
      end

      it "redirects to the created itinerary" do
        post itineraries_url, params: { itinerary: valid_attributes }
        expect(response).to redirect_to(itinerary_url(Itinerary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Itinerary" do
        expect {
          post itineraries_url, params: { itinerary: invalid_attributes }
        }.to change(Itinerary, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post itineraries_url, params: { itinerary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested itinerary" do
        itinerary = Itinerary.create! valid_attributes
        patch itinerary_url(itinerary), params: { itinerary: new_attributes }
        itinerary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the itinerary" do
        itinerary = Itinerary.create! valid_attributes
        patch itinerary_url(itinerary), params: { itinerary: new_attributes }
        itinerary.reload
        expect(response).to redirect_to(itinerary_url(itinerary))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        itinerary = Itinerary.create! valid_attributes
        patch itinerary_url(itinerary), params: { itinerary: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested itinerary" do
      itinerary = Itinerary.create! valid_attributes
      expect {
        delete itinerary_url(itinerary)
      }.to change(Itinerary, :count).by(-1)
    end

    it "redirects to the itineraries list" do
      itinerary = Itinerary.create! valid_attributes
      delete itinerary_url(itinerary)
      expect(response).to redirect_to(itineraries_url)
    end
  end
end
